version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/src/platform/frontend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/src/platform/backend"
    schedule:
      interval: "weekly"
